name: artic-rabv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
#  - artic=1.2.3
  - artic-network::rampart=1.2.0
  - snakemake-minimal=5.8.1
  #- datamash=1.1.0
  - tabix
 # - bcftools<=1.13
  - mafft
  - nomkl
  - pandas
  - pip
  - pyvcf
  - snp-sites
  - muscle
  - pip:
     - git+https://github.com/kirstyn/fieldbioinformatics.git@1.3.0-dev #egg=artic
     - medaka==1.8.1
     - pysam
     - seaborn
